export interface IWoolworthsProductJson {
	TileID: number
	Stockcode: number
	Barcode: string
	GtinFormat: number
	CupPrice: number
	InstoreCupPrice: number
	CupMeasure: string
	CupString: string
	InstoreCupString: string
	HasCupPrice: boolean
	InstoreHasCupPrice: boolean
	Price: number
	InstorePrice: number
	Name: string
	DisplayName: string
	UrlFriendlyName: string
	Description: string
	SmallImageFile: string
	MediumImageFile: string
	LargeImageFile: string
	IsNew: boolean
	IsHalfPrice: false
	IsOnlineOnly: false
	IsOnSpecial: boolean
	InstoreIsOnSpecial: boolean
	IsEdrSpecial: boolean
	SavingsAmount: number
	InstoreSavingsAmount: number
	WasPrice: number
	InstoreWasPrice: number
	QuantityInTrolley: number
	Unit: string
	MinimumQuantity: number
	HasBeenBoughtBefore: boolean
	IsInTrolley: boolean
	Source: string
	SupplyLimit: number
	ProductLimit: number
	MaxSupplyLimitMessage: string
	IsRanged: boolean
	IsInStock: boolean
	PackageSize: string
	IsPmDelivery: boolean
	IsForCollection: boolean
	IsForDelivery: boolean
	IsForExpress: boolean
	ProductRestrictionMessage: null
	ProductWarningMessage: null
	CentreTag: {
		TagContent: null
		TagLink: null
		FallbackText: null
		TagType: "None"
		MultibuyData: null
		MemberPriceData: null
		TagContentText: null
		DualImageTagContent: null
		PromotionType: string
		IsRegisteredRewardCardPromotion: boolean
	}
	IsCentreTag: false
	ImageTag: {
		TagContent: string
		TagLink: null
		FallbackText: string
		TagType: string
		MultibuyData: null
		MemberPriceData: null
		TagContentText: null
		DualImageTagContent: null
		PromotionType: string
		IsRegisteredRewardCardPromotion: boolean
	}
	HeaderTag: null
	HasHeaderTag: boolean
	UnitWeightInGrams: number
	SupplyLimitMessage: string
	SmallFormatDescription: string
	FullDescription: string
	IsAvailable: boolean
	InstoreIsAvailable: boolean
	IsPurchasable: boolean
	InstoreIsPurchasable: boolean
	AgeRestricted: boolean
	DisplayQuantity: number
	RichDescription: null
	HideWasSavedPrice: boolean
	SapCategories: null
	Brand: null
	IsRestrictedByDeliveryMethod: boolean
	FooterTag: {
		TagContent: null
		TagLink: null
		FallbackText: null
		TagType: "None"
		MultibuyData: null
		MemberPriceData: null
		TagContentText: null
		DualImageTagContent: null
		PromotionType: "NOT_SET"
		IsRegisteredRewardCardPromotion: false
	}
	IsFooterEnabled: false
	Diagnostics: string
	IsBundle: boolean
	IsInFamily: boolean
	ChildProducts: null
	UrlOverride: null
	AdditionalAttributes: {
		boxedcontents: null
		addedvitaminsandminerals: boolean
		sapdepartmentname: string
		spf: null
		haircolour: null
		lifestyleanddietarystatement: null
		sapcategoryname: string
		skintype: null
		importantinformation: null
		allergystatement: null
		productdepthmm: null
		skincondition: null
		ophthalmologistapproved: null
		healthstarrating: string
		hairtype: null
		"fragrance-free": null
		sapsegmentname: string
		suitablefor: null
		PiesProductDepartmentsjson: string
		piessubcategorynamesjson: string
		sapsegmentno: string
		productwidthmm: null
		contains: null
		sapsubcategoryname: string
		dermatologisttested: null
		wool_productpackaging: null
		dermatologicallyapproved: null
		specialsgroupid: null
		productimages: string
		productheightmm: null
		"r&r_hidereviews": null
		microwavesafe: boolean
		"paba-free": null
		lifestyleclaim: null
		alcoholfree: null
		tgawarning: null
		activeconstituents: null
		microwaveable: boolean
		"soap-free": null
		countryoforigin: null
		isexcludedfromsubstitution: boolean
		productimagecount: string
		"r&r_loggedinreviews": null
		"anti-dandruff": null
		"servingsize-total-nip": null
		tgahealthwarninglink: null
		allergenmaybepresent: null
		PiesProductDepartmentNodeId: string
		parabenfree: boolean
		vendorarticleid: null
		containsgluten: boolean
		containsnuts: boolean
		ingredients: null
		colour: null
		manufacturer: null
		sapcategoryno: string
		storageinstructions: null
		tgawarnings: null
		piesdepartmentnamesjson: string
		brand: string
		oilfree: null
		fragrance: null
		antibacterial: boolean
		"non-comedogenic": null
		antiseptic: boolean
		bpafree: boolean
		vendorcostprice: null
		description: string
		sweatresistant: null
		sapsubcategoryno: string
		antioxidant: boolean
		claims: null
		phbalanced: null
		wool_dietaryclaim: null
		ophthalmologisttested: null
		sulfatefree: boolean
		piescategorynamesjson: string
		"servingsperpack-total-nip": null
		nutritionalinformation: null
		ovencook: boolean
		vegetarian: boolean
		"hypo-allergenic": null
		timer: null
		dermatologistrecommended: null
		sapdepartmentno: string
		allergencontains: null
		waterresistant: null
		friendlydisclaimer: null
		recyclableinformation: null
		usageinstructions: null
		freezable: boolean
	}
	DetailsImagePaths: [string]
	Variety: null
	Rating: {
		ReviewCount: number
		RatingCount: number
		RatingSum: number
		OneStarCount: number
		TwoStarCount: number
		ThreeStarCount: number
		FourStarCount: number
		FiveStarCount: number
		Average: number
		OneStarPercentage: number
		TwoStarPercentage: number
		ThreeStarPercentage: number
		FourStarPercentage: number
		FiveStarPercentage: number
	}
	HasProductSubs: boolean
	IsSponsoredAd: boolean
	AdID: null
	AdIndex: null
	AdStatus: null
	IsMarketProduct: false
	IsGiftable: false
	Vendor: null
	Untraceable: false
	ThirdPartyProductInfo: null
	MarketFeatures: null
	MarketSpecifications: null
	SupplyLimitSource: string
	Tags: [
		{
			Content: {
				Type: string
				Position: string
				Attributes: {
					ImagePath: string
					FallbackText: string
				}
			}
			TemplateId: null
			Metadata: null
		}
	]
	IsPersonalisedByPurchaseHistory: false
	IsFromFacetedSearch: boolean
	NextAvailabilityDate: string
	NumberOfSubstitutes: number
	IsPrimaryVariant: boolean
	VariantGroupId: number
	HasVariants: boolean
	VariantTitle: null
	IsTobacco: boolean
	IsB2BExtendedRangeSapCategory: boolean
}

export interface IWoolworthsCategoryBundleJson {
	Bundles: {
		Products: IWoolworthsProductJson[]
		Name: string
		DisplayName: string
	}[]
}
