export interface WwsProduct {
  TileID: number;
  Stockcode: number;
  Barcode: string;
  GtinFormat: number;
  Name: string;
  DisplayName: string;
  Description: string;
  UrlFriendlyName: string;
  SmallImageFile: string;
  MediumImageFile: string;
  LargeImageFile: string;
  Brand: string | null;
  Variety: string;
  PackageSize: string;
  Unit: string;
  MinimumQuantity: number;
  Price: number | null;
  InstorePrice: number | null;
  WasPrice: number | null;
  InstoreWasPrice: number | null;
  CupPrice: number | null;
  InstoreCupPrice: number | null;
  CupMeasure: string;
  CupString: string;
  InstoreCupString: string;
  HasCupPrice: boolean;
  InstoreHasCupPrice: boolean;
  SavingsAmount: number | null;
  InstoreSavingsAmount: number | null;
  IsNew: boolean;
  IsHalfPrice: boolean;
  IsOnlineOnly: boolean;
  IsOnSpecial: boolean;
  InstoreIsOnSpecial: boolean;
  IsEdrSpecial: boolean;
  IsAvailable: boolean;
  InstoreIsAvailable: boolean;
  IsPurchasable: boolean;
  InstoreIsPurchasable: boolean;
  AgeRestricted: boolean;
  SupplyLimit: number;
  ProductLimit: number;
  SupplyLimitSource: string;
  MaxSupplyLimitMessage: string;
  IsRanged: boolean;
  IsInStock: boolean;
  IsPmDelivery: boolean;
  IsForCollection: boolean;
  IsForDelivery: boolean;
  IsForExpress: boolean;
  ProductRestrictionMessage: string | null;
  ProductWarningMessage: string | null;
  AdditionalAttributes: {
    nutritionalinformation?: string | null;
    allergencontains?: string | null;
    allergenmaybepresent?: string | null;
    ingredients?: string | null;
    storageinstructions?: string | null;
    countryoforigin?: string | null;
    description?: string | null;
    lifestyleanddietarystatement?: string | null;
    allergystatement?: string | null;
    healthstarrating?: string | null;
    [key: string]: string | null | undefined;
  };
  Rating: {
    ReviewCount: number;
    RatingCount: number;
    RatingSum: number;
    OneStarCount: number;
    TwoStarCount: number;
    ThreeStarCount: number;
    FourStarCount: number;
    FiveStarCount: number;
    Average: number;
    OneStarPercentage: number;
    TwoStarPercentage: number;
    ThreeStarPercentage: number;
    FourStarPercentage: number;
    FiveStarPercentage: number;
  };
  IsBundle: boolean;
  IsInFamily: boolean;
  ChildProducts: null;
  UrlOverride: string | null;
  IsMarketProduct: boolean;
  IsGiftable: boolean;
  IsTobacco: boolean;
}
